version: 0.2

phases:
  install:
    commands:
      - echo "Install Prequisites"
      # Parameters passed by the pipeline
      - echo $S3_DEPLOYMENT_BUCKET
      - echo $CF_EXECUTION_ROLE
      - echo $KMS_KEY_ID
      - cd $CODEBUILD_SRC_DIR
      - mkdir /final-build-location
      # Install SAM CLI
      - python --version
      - pip --version
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - sam --version
  build:
    commands:
      - echo "Start Building"
      - cd $CODEBUILD_SRC_DIR
      - aws configure --profile default set region us-east-1
      - aws configure --profile deploy-profile set credential_source EcsContainer
      - aws configure --profile deploy-profile set role_session_name $(date '+%Y%m%d%H%M%S%3N')
      - aws configure --profile deploy-profile set role_arn $CF_EXECUTION_ROLE
      # SAM Package
      - |
        sam package \
        --template-file ./cf-goldmine-CloudWatchPagerDutySAM.yml \
        --s3-bucket $S3_DEPLOYMENT_BUCKET \
        --s3-prefix DEV \
        --kms-key-id $KMS_KEY_ID \
        --output-template-file /final-build-location/package.yaml \
        --profile deploy-profile
      # Deploy package built above
      - |
        sam deploy \
        --template-file /final-build-location/package.yaml \
        --stack-name cf-goldmine-emr-Monitoring.yml \
        --profile deploy-profile \
        --capabilities CAPABILITY_NAMED_IAM
      - echo "Build complete"
artifacts:
  files:
    - package.yaml
  discard-paths: no
  base-directory: /final-build-location